name: caesar_encryptor
description: >
  A Dart package for encrypting and decrypting text using the Caesar cipher. 
  Supports multiple alphabets and flexible output formatting.

version: 0.1.0
homepage: https://github.com/itschillipill/caesar_encryptor
repository: https://github.com/itschillipill/caesar_encryptor
issue_tracker: https://github.com/itschillipill/caesar_encryptor/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # No external dependencies

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0